Install Mono 5.x in the CI environment

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -10,11 +10,6 @@ cd $APP_HOME
 
 check_dependencies() {
     set +e
-    TEST=$(which mono)
-    if [[ -z "$TEST" ]]; then
-        echo "ERROR: 'mono' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
-        exit 1
-    fi
 
     TEST=$(which nuget)
     if [[ -z "$TEST" ]]; then
@@ -22,9 +17,21 @@ check_dependencies() {
         exit 1
     fi
 
+    TEST=$(which msbuild)
+    if [[ -z "$TEST" ]]; then
+        echo "ERROR: 'msbuild' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
+        exit 1
+    fi
+
     TEST=$(which dotnet)
     if [[ -z "$TEST" ]]; then
         echo "ERROR: 'dotnet' command not found. Install .NET Core first (https://dotnet.github.io)."
+        exit 1
+    fi
+
+    TEST=$(which mono)
+    if [[ -z "$TEST" ]]; then
+        echo "ERROR: 'mono' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
         exit 1
     fi
     set -e
