Update contribution notes and scripts

diff --git a/scripts/compile b/scripts/compile
--- a/scripts/compile
+++ b/scripts/compile
@@ -6,11 +6,7 @@ source "$APP_HOME/scripts/.functions.sh"
 cd $APP_HOME
 
 check_dependencies() {
-    TEST=$(which mono)
-    if [[ -z "$TEST" ]]; then
-        echo "ERROR: 'mono' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
-        exit 1
-    fi
+    set +e
 
     TEST=$(which nuget)
     if [[ -z "$TEST" ]]; then
@@ -18,11 +14,12 @@ check_dependencies() {
         exit 1
     fi
 
-    TEST=$(which dotnet)
+    TEST=$(which msbuild)
     if [[ -z "$TEST" ]]; then
-        echo "ERROR: 'dotnet' command not found. Install .NET Core first (https://dotnet.github.io)."
+        echo "ERROR: 'msbuild' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
         exit 1
     fi
+    set -e
 }
 
 failed() {
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -8,6 +8,31 @@ set -e
 APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
 cd $APP_HOME
 
+check_dependencies() {
+    set +e
+
+    TEST=$(which nuget)
+    if [[ -z "$TEST" ]]; then
+        echo "ERROR: 'nuget' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
+        exit 1
+    fi
+
+    TEST=$(which msbuild)
+    if [[ -z "$TEST" ]]; then
+        echo "ERROR: 'msbuild' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
+        exit 1
+    fi
+
+    TEST=$(which mono)
+    if [[ -z "$TEST" ]]; then
+        echo "ERROR: 'mono' command not found. Install Mono 5.x first (http://www.mono-project.com/docs/about-mono/releases/5.0.0)."
+        exit 1
+    fi
+    set -e
+}
+
+check_dependencies
+
 echo "Building..."
 nuget restore
 msbuild /m /p:Configuration=$CONFIGURATION /verbosity:quiet
