Save simulations in the storage (#32)
* Store simulations using the storage adapter
* Implement device bootstrap scenario: when a new device is created, mark it as a simulated device and report some properties like device type, messages schema, and initial location.
* Remove dependency on IoT Hub manager and access IoT Hub directly
* Refactor state machine to reduce complexity and reuse code
* Add launch settings for Visual Studio
* Remove env var used for the web service TCP port
* Improve logging of exceptions to avoid log flooding
* Fix messages format, to always use the “_unit” convention
* Add JSON config checks

diff --git a/scripts/env-vars-check b/scripts/env-vars-check
--- a/scripts/env-vars-check
+++ b/scripts/env-vars-check
@@ -4,3 +4,8 @@ if [[ -z "$PCS_IOTHUB_CONNSTRING" ]]; then
     echo "Error: the PCS_IOTHUB_CONNSTRING environment variable is not defined."
     exit 1
 fi
+
+if [[ -z "$PCS_STORAGEADAPTER_WEBSERVICE_URL" ]]; then
+    echo "Error: the PCS_STORAGEADAPTER_WEBSERVICE_URL environment variable is not defined."
+    exit 1
+fi
