Improve env. vars documentation and scripts

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -101,6 +101,16 @@ run_simulation() {
 run_iothubmanager() {
     check_dependency_docker
 
+    if [[ -z "$PCS_IOTHUBMANAGER_WEBSERVICE_PORT" ]]; then
+        echo "Error: the PCS_IOTHUBMANAGER_WEBSERVICE_PORT environment variable is not defined."
+        exit 1
+    fi
+
+    if [[ -z "$PCS_IOTHUB_CONN_STRING" ]]; then
+        echo "Error: the PCS_IOTHUB_CONN_STRING environment variable is not defined."
+        exit 1
+    fi
+
     VERSION=latest
     docker run -it -p $PCS_IOTHUBMANAGER_WEBSERVICE_PORT:$PCS_IOTHUBMANAGER_WEBSERVICE_PORT \
         -e PCS_IOTHUBMANAGER_WEBSERVICE_PORT=$PCS_IOTHUBMANAGER_WEBSERVICE_PORT \
